export const DRUG_CATEGORIES = [
  { value: 'antibiotic',               label: 'Antibiotic' },
  { value: 'antifungal',               label: 'Antifungal' },
  { value: 'antiviral',                label: 'Antiviral' },
  { value: 'analgesic-nsaid',          label: 'Analgesic / NSAID' },
  { value: 'cardiovascular',           label: 'Cardiovascular' },
  { value: 'respiratory',              label: 'Respiratory' },
  { value: 'gastrointestinal',         label: 'Gastrointestinal' },
  { value: 'endocrine-metabolic',      label: 'Endocrine & Metabolic' },
  { value: 'neurological-psychiatric', label: 'Neurological / Psychiatric' },
  { value: 'musculoskeletal',          label: 'Musculoskeletal' },
  { value: 'vitamins-minerals',        label: 'Vitamins & Minerals' },
  { value: 'dermatological',           label: 'Dermatological' },
  { value: 'ophthalmic-otic',          label: 'Ophthalmic / Otic' },
  { value: 'urological',               label: 'Urological' },
  { value: 'obstetric-gynecological',  label: 'Obstetric & Gynaecological' },
  { value: 'antiparasitic',            label: 'Antiparasitic' },
  { value: 'other',                    label: 'Other' },
]
