export const DRUG_FORMS = [
  { value: 'tablet' },
  { value: 'capsule' },
  { value: 'syrup' },
  { value: 'suspension' },
  { value: 'drops' },
  { value: 'injection' },
  { value: 'cream' },
  { value: 'ointment' },
  { value: 'gel' },
  { value: 'suppository' },
  { value: 'inhaler' },
  { value: 'patch' },
  { value: 'sachet' },
  { value: 'solution' },
  { value: 'piece' },
  { value: 'vial' },
  { value: 'ampoule' },
  { value: 'effervescent' },
  { value: 'spray' },
  { value: 'eye drops' },
  { value: 'oral drops' },
  { value: 'ear drops' },
  { value: 'nasal drops' },
  { value: 'mouth drops' },
  { value: 'lotion' },
  { value: 'shampoo' },
  { value: 'mouth wash' },
  { value: 'vaginal douche' },
  { value: 'syringe' },
  { value: 'pen' },
  { value: 'soap' },
  { value: 'powder' },
  { value: 'serum' },
  { value: 'hair oil' },
  { value: 'oil' },
  { value: 'bottle' },
  { value: 'film' },
  { value: 'antiseptic solution' },
  { value: 'inhalation solution' },
  { value: 'paint' },
  { value: 'enema' },
  { value: 'eye ointment' },
  { value: 'vaccine' },
  { value: 'facial wash' },
  { value: 'conditioner' },
  { value: 'foam' },
  { value: 'gauze dressing' },
  { value: 'wipes' },
  { value: 'lozenges' },
  { value: 'other' },
].map(f => ({
  ...f,
  label: f.value.charAt(0).toUpperCase() + f.value.slice(1),
}))

// Base-form abbreviation for the drug card title suffix (drug_card_title_suffix
// plan, step B.1 / decision 4.40, locked). Only forms with a genuine, standard
// pharmacy short form get abbreviated (4.36) — the rest just use their plain
// capitalized word, same as DRUG_FORMS.label above.
export const DRUG_FORM_SUFFIXES = {
  'tablet':               'Tab.',
  'capsule':              'Cap.',
  'syrup':                'Syrup',
  'suspension':           'Susp.',
  'drops':                'Drops',
  'injection':            'Inj.',
  'cream':                'Cream',
  'ointment':             'Oint.',
  'gel':                  'Gel',
  'suppository':          'Supp.',
  'inhaler':              'Inhaler',
  'patch':                'Patch',
  'sachet':               'Sachet',
  'solution':             'Sol.',
  'piece':                'Piece',
  'vial':                 'Vial',
  'ampoule':              'Amp.',
  'effervescent':         'Eff.',
  'spray':                'Spray',
  'eye drops':            'Eye Drops',
  'oral drops':           'Oral Drops',
  'ear drops':            'Ear Drops',
  'nasal drops':          'Nasal Drops',
  'mouth drops':          'Mouth Drops',
  'lotion':               'Lotion',
  'shampoo':              'Shampoo',
  'mouth wash':           'Mouth Wash',
  'vaginal douche':       'Vaginal Douche',
  'syringe':              'Syringe',
  'pen':                  'Pen',
  'soap':                 'Soap',
  'powder':               'Powder',
  'serum':                'Serum',
  'hair oil':             'Hair Oil',
  'oil':                  'Oil',
  'bottle':               'Bottle',
  'film':                 'Film',
  'antiseptic solution':  'Antiseptic Sol.',
  'inhalation solution':  'Inhalation Sol.',
  'paint':                'Paint',
  'enema':                'Enema',
  'eye ointment':         'Eye Oint.',
  'vaccine':              'Vaccine',
  'facial wash':          'Facial Wash',
  'conditioner':          'Conditioner',
  'foam':                 'Foam',
  'gauze dressing':       'Gauze Dressing',
  'wipes':                'Wipes',
  'lozenges':             'Lozenges',
  'other':                'Other',
}

export const DRUG_ROUTES = [
  { value: 'oral',        label: 'Oral' },
  { value: 'oral.solid',  label: 'Oral (solid)' },
  { value: 'oral.liquid', label: 'Oral (liquid)' },
  { value: 'injection',   label: 'Injection' },
  { value: 'topical',     label: 'Topical' },
  { value: 'inhaled',     label: 'Inhaled' },
  { value: 'inhalation',  label: 'Inhalation' },
  { value: 'rectal',      label: 'Rectal' },
  { value: 'ocular',      label: 'Ocular' },
  { value: 'eye',         label: 'Eye' },
  { value: 'otic',        label: 'Otic' },
  { value: 'ear',         label: 'Ear' },
  { value: 'spray',       label: 'Spray' },
  { value: 'vaginal',     label: 'Vaginal' },
  { value: 'mouth',       label: 'Mouth' },
  { value: 'nose',        label: 'Nose' },
  { value: 'nasal',       label: 'Nasal' },
  { value: 'unknown',     label: 'Unknown' },
  { value: 'other',       label: 'Other' },
]

// Tick-list detail options for when route = 'injection'. An admin can select
// more than one (e.g. a drug given both IV and IM). Storage for multiple
// selected values is a separate, not-yet-built decision (see plan doc —
// `formulations.route_details` array column, scheduled for Phase 1B/2A).
export const INJECTION_ROUTE_DETAILS = [
  { value: 'iv',            label: 'IV' },
  { value: 'im',            label: 'IM' },
  { value: 'subcutaneous',  label: 'Subcutaneous' },
  { value: 'intrathecal',   label: 'Intrathecal' },
  { value: 'intravascular', label: 'Intravascular' },
]
